const api=require('../../utils/api');const {parks,genders,roles}=require('../../utils/constants');
Page({data:{user:null,stores:[],storeIndex:0,storeMissing:false,parks,genders,nickname:'',parkIndex:0,parkDetail:'',dormRoom:'',genderIndex:0,roleName:'',error:'',busy:false},
 onShow(){this.load();},async load(){try{const me=await api.guard();if(!me)return;const s=await api.call('public.stores');const list=(s&&s.items)||[];const i=list.findIndex(x=>x._id===me.user.storeId);this.setData({...me,stores:list,storeIndex:i<0?0:i,storeMissing:i<0,nickname:me.user.nickname,parkIndex:Math.max(0,parks.indexOf(me.user.park)),parkDetail:me.user.parkDetail||'',dormRoom:me.user.dormRoom||'',genderIndex:genders.indexOf(me.user.gender),roleName:roles[me.user.role],error:''});}catch(e){this.setData({error:e.message});}},
 input(e){this.setData({[e.currentTarget.dataset.key]:e.detail.value});}, select(e){this.setData({[e.currentTarget.dataset.key]:Number(e.detail.value)});},
 async save(){if(this.data.busy)return;const park=parks[this.data.parkIndex];if(park==='其它'&&!this.data.parkDetail.trim()){this.setData({error:'选择「其它」时，请填写具体园区或楼栋'});return;}this.setData({busy:true,error:''});try{const r=await api.call('profile.update',{nickname:this.data.nickname,park,...(park==='其它'?{parkDetail:this.data.parkDetail}:{}),dormRoom:this.data.dormRoom,gender:genders[this.data.genderIndex]});this.setData(r);wx.showToast({title:'已保存'});}catch(e){this.setData({error:e.message});}finally{this.setData({busy:false});}},
 // 客户自己换服务门店：门店停用/搬迁时不该被卡死。只换归属，历史会话留在原门店。
 // 取消选择时不更新 storeIndex，picker 是受控组件，显示会回到当前门店。
 async pickStore(e){if(this.data.busy)return;const target=this.data.stores[Number(e.detail.value)];if(!target||target._id===((this.data.user||{}).storeId))return;const r=await wx.showModal({title:'更换服务门店',content:`切换到「${target.name}」后，新对话会发给这家店；你与原门店的历史记录仍保留在原来那家。`});if(!r.confirm)return;this.setData({busy:true,error:''});try{await api.call('store.switch',{storeId:target._id});await this.load();wx.showToast({title:'已更换门店'});}catch(err){this.setData({error:err.message});}finally{this.setData({busy:false});}},
 async logout(){const r=await wx.showModal({title:'退出登录',content:'退出后需重新登录。'});if(!r.confirm)return;try{await api.call('logout');api.clear();wx.reLaunch({url:'/pages/auth/index'});}catch(e){this.setData({error:e.message});}},
 staff(){wx.navigateTo({url:'/pages/staff/index'});},admin(){wx.navigateTo({url:'/pages/admin/index'});},orders(){wx.navigateTo({url:'/pages/order/mine/index'});},runner(){const st=((this.data.user||{}).runner||{}).status;wx.navigateTo({url:st==='approved'?'/pages/runner/hall/index':'/pages/runner/apply/index'});},privacy(){wx.navigateTo({url:'/pages/privacy/index'});}
});
