const api=require('../../utils/api');const config=require('../../config');const {roles,categories}=require('../../utils/constants');
const tables=['users','stores','conversations','messages','notifications','services','banners','auditLogs'];
Page({data:{tab:'users',users:[],stores:[],storeOptions:[],keyword:'',services:[],banners:[],applicants:[],runnerFeeYuan:3,rows:[],tables,tableIndex:0,error:'',loading:false,busy:false,page:0,more:false,edit:null,roleOptions:['客户','门店'],roleIndex:0,storeIndex:0,storeId:'',storeName:'',editingStore:false,storeEnabled:true,serviceId:'',serviceName:'',serviceDesc:'',serviceEnabled:true,editingService:false,categoryOptions:Object.values(categories),categoryKeys:Object.keys(categories),categoryIndex:0,bannerId:'',bannerTitle:'',bannerSubtitle:'',bannerWeight:50,bannerEnabled:true,editingBanner:false,bannerMediaType:'none',bannerMedia:'',versions:['开发版','体验版','正式版'],versionIndex:1,qrStore:0,qr:''},
 onShow(){this.start();},async start(){try{const me=await api.guard(['admin']);if(!me)return;this.setData({demoMode:!!me.demoMode});await this.loadStores();await this.load(false,true);}catch(e){this.setData({error:e.message});}},
 // storeOptions 只留营业中的门店：账户编辑、入口码这些地方只能选启用门店，把停用的也列出来是误导。
 async loadStores(){const r=await api.call('admin.stores');this.setData({stores:r.items,storeOptions:r.items.filter(s=>s.enabled)});},
 // 跑腿资质：只列待审核的申请，顺带把当前跑腿费读出来（单位分转成元显示）。
 async loadRunner(){const r=await api.call('staff.customers',{page:0});const c=await api.call('order.config');this.setData({applicants:r.items.filter(u=>u.runner&&u.runner.status==='pending').map(u=>({...u,appliedText:api.time(u.runner.appliedAt)})),runnerFeeYuan:c.runnerFee/100,more:false});},
 async review(e){if(this.data.busy)return;const id=e.currentTarget.dataset.id,result=e.currentTarget.dataset.result;let reason='';if(result==='rejected'){const r=await wx.showModal({title:'驳回申请',editable:true,placeholderText:'填写驳回理由，申请人能看到'});if(!r.confirm)return;reason=(r.content||'').trim();if(!reason){this.setData({error:'驳回需要写明理由'});return;}}else{const r=await wx.showModal({title:'通过申请',content:'通过后该用户就能接单；证件照片会立即从云存储删除，只保留已核验标记。'});if(!r.confirm)return;}this.setData({busy:true,error:''});try{await api.call('admin.runnerReview',{id,result,reason});await this.loadRunner();wx.showToast({title:result==='approved'?'已通过':'已驳回'});}catch(err){this.setData({error:err.message});}finally{this.setData({busy:false});}},
 async saveFee(){if(this.data.busy)return;const yuan=Number(this.data.runnerFeeYuan);if(!Number.isFinite(yuan)||yuan<0||yuan>1000){this.setData({error:'跑腿费需为 0 到 1000 元之间的数字'});return;}this.setData({busy:true,error:''});try{await api.call('admin.runnerFee',{fee:Math.round(yuan*100)});wx.showToast({title:'已保存'});}catch(err){this.setData({error:err.message});}finally{this.setData({busy:false});}},
 tab(e){if(this.data.loading)return;this.setData({tab:e.currentTarget.dataset.tab,page:0,users:[],services:[],banners:[],rows:[],edit:null,error:''});this.load(false,true);},
 search(){if(this.data.loading)return;this.setData({users:[],page:0});this.load(false,true);},
 async load(e,reset=false){if(this.data.loading)return;this.setData({loading:true,error:''});const page=reset?0:this.data.page+1;try{if(this.data.tab==='users'){const r=await api.call('staff.customers',{page,keyword:this.data.keyword});const users=r.items.map(u=>({...u,roleName:roles[u.role]}));this.setData({users:reset?users:this.data.users.concat(users),page,more:users.length===20});}else if(this.data.tab==='database'){const r=await api.call('admin.inspect',{collection:tables[this.data.tableIndex],page});const rows=r.items.map(x=>({_id:x._id,json:JSON.stringify(x,null,2)}));this.setData({rows:reset?rows:this.data.rows.concat(rows),page,more:rows.length===20});}else if(this.data.tab==='services'){const r=await api.call('admin.services');this.setData({services:r.items,more:false});}else if(this.data.tab==='banners'){const r=await api.call('admin.banners');this.setData({banners:r.items,more:false});}else if(this.data.tab==='runner'){await this.loadRunner();}else{await this.loadStores();this.setData({more:false});}}catch(e){this.setData({error:e.message});}finally{this.setData({loading:false});}},
 editUser(e){const u=this.data.users.find(x=>x._id===e.currentTarget.dataset.id);this.setData({edit:{...u},roleIndex:u.role==='store'?1:0,storeIndex:Math.max(0,this.data.storeOptions.findIndex(s=>s._id===u.storeId))},()=>wx.pageScrollTo({selector:'#user-editor',duration:200}));},
 select(e){this.setData({[e.currentTarget.dataset.key]:Number(e.detail.value)});},userEnabled(e){this.setData({'edit.enabled':e.detail.value});},close(){this.setData({edit:null});},
 async saveUser(){if(this.data.busy)return;const store=this.data.storeOptions[this.data.storeIndex];if(!store){this.setData({error:'请先创建门店'});return;}const r=await wx.showModal({title:'保存账户权限',content:this.data.demoMode?'修改后需重新选择该演示身份，原有会话保留在原门店。':'修改后该用户需重新验证手机号登录。原有会话保留在原门店。'});if(!r.confirm)return;this.setData({busy:true,error:''});try{await api.call('admin.userUpdate',{id:this.data.edit._id,enabled:this.data.edit.enabled,role:this.data.roleIndex===1?'store':'customer',storeId:store._id});this.setData({edit:null});await this.load(false,true);}catch(e){this.setData({error:e.message});}finally{this.setData({busy:false});}},
 input(e){this.setData({[e.currentTarget.dataset.key]:e.detail.value});},storeEnabled(e){this.setData({storeEnabled:e.detail.value});},
 editStore(e){const s=this.data.stores.find(x=>x._id===e.currentTarget.dataset.id);this.setData({storeId:s._id,storeName:s.name,storeEnabled:s.enabled,editingStore:true});},
 newStore(){this.setData({storeId:'',storeName:'',storeEnabled:true,editingStore:false});},
 async saveStore(){if(this.data.busy)return;if(!this.data.storeEnabled){const s=this.data.stores.find(x=>x._id===this.data.storeId);const n=(s&&s.userCount)||0;const r=await wx.showModal({title:'停用门店',content:n?`这家门店下还有 ${n} 个账户。停用后他们无法联系门店、员工也无法登录，建议先把他们转到其他门店。`:'该门店将不能接收新注册，门店员工登录和相关会话也会停用。'});if(!r.confirm)return;}this.setData({busy:true,error:''});try{await api.call('admin.storeSave',{id:this.data.storeId,name:this.data.storeName,enabled:this.data.storeEnabled});await this.loadStores();this.newStore();wx.showToast({title:'已保存'});}catch(e){this.setData({error:e.message});}finally{this.setData({busy:false});}},
 async removeStore(e){if(this.data.busy)return;const id=e.currentTarget.dataset.id;const store=this.data.stores.find(x=>x._id===id);const r=await wx.showModal({title:'删除门店',content:`删除「${store?store.name:id}」不可恢复。若只是不想让它出现在注册页，请改用「停用」，停用会保留历史记录。`});if(!r.confirm)return;this.setData({busy:true,error:''});try{await api.call('admin.storeDelete',{id});if(this.data.storeId===id)this.newStore();await this.loadStores();wx.showToast({title:'已删除'});}catch(err){this.setData({error:err.message});}finally{this.setData({busy:false});}},
  editService(e){const s=this.data.services.find(x=>x._id===e.currentTarget.dataset.id);this.setData({serviceId:s._id,serviceName:s.name,serviceDesc:s.description,serviceEnabled:s.enabled,categoryIndex:Math.max(0,this.data.categoryKeys.indexOf(s.category)),editingService:true});},
 newService(){this.setData({serviceId:'',serviceName:'',serviceDesc:'',serviceEnabled:true,categoryIndex:0,editingService:false});},
 serviceEnabled(e){this.setData({serviceEnabled:e.detail.value});},
 async saveService(){if(this.data.busy)return;const name=this.data.serviceName.trim(),description=this.data.serviceDesc.trim();if(!name||!description){this.setData({error:'请填写服务名称和说明'});return;}this.setData({busy:true,error:''});try{await api.call('admin.serviceSave',{id:this.data.serviceId,name,description,category:this.data.categoryKeys[this.data.categoryIndex],enabled:this.data.serviceEnabled});this.newService();await this.load(false,true);wx.showToast({title:'已保存'});}catch(e){this.setData({error:e.message});}finally{this.setData({busy:false});}},
 async removeService(e){if(this.data.busy)return;const id=e.currentTarget.dataset.id;const r=await wx.showModal({title:'删除服务',content:'删除后该服务会立即从首页服务列表移除，且无法恢复。如需暂时隐藏，请改用停用。'});if(!r.confirm)return;this.setData({busy:true,error:''});try{await api.call('admin.serviceDelete',{id});if(this.data.serviceId===id)this.newService();await this.load(false,true);wx.showToast({title:'已删除'});}catch(err){this.setData({error:err.message});}finally{this.setData({busy:false});}},
 editBanner(e){const b=this.data.banners.find(x=>x._id===e.currentTarget.dataset.id);this.setData({bannerId:b._id,bannerTitle:b.title,bannerSubtitle:b.subtitle,bannerWeight:b.weight,bannerEnabled:b.enabled,editingBanner:true,bannerMediaType:b.mediaType||'none',bannerMedia:b.mediaFileID||''});},
 newBanner(){this.setData({bannerId:'',bannerTitle:'',bannerSubtitle:'',bannerWeight:50,bannerEnabled:true,editingBanner:false,bannerMediaType:'none',bannerMedia:''});},
 bannerEnabled(e){this.setData({bannerEnabled:e.detail.value});},
 // 选择海报图片或短视频（专业同事做好的素材）。图片≤10MB，视频≤60MB、≤60秒。
 // 真实环境：保存时才上传云存储，避免选了又取消产生孤儿文件；演示模式直接用本地临时路径预览。
 chooseBannerMedia(){if(this.data.busy)return;if(!wx.chooseMedia){this.setData({error:'当前基础库不支持选择素材，请升级微信开发者工具后重试'});return;}wx.chooseMedia({count:1,mediaType:['image','video'],sourceType:['album'],maxDuration:60,sizeType:['compressed'],success:r=>{const f=(r.tempFiles||[])[0];if(!f){this.setData({error:'没有取到素材文件，请重试'});return;}const isImage=f.fileType==='image';if(isImage&&f.size>10*1024*1024){this.setData({error:'图片不能超过 10MB'});return;}if(!isImage&&f.duration>60){this.setData({error:'视频不能超过 60 秒'});return;}if(!isImage&&f.size>60*1024*1024){this.setData({error:'视频不能超过 60MB'});return;}this.setData({bannerMediaType:isImage?'image':'video',bannerMedia:f.tempFilePath,error:''});},fail:err=>{const msg=(err&&err.errMsg)||'未知原因';if(msg.indexOf('cancel')>-1)return;this.setData({error:'选择素材失败：'+msg});console.error('chooseMedia failed',err);}});},
 removeBannerMedia(){this.setData({bannerMediaType:'none',bannerMedia:''});},
 async saveBanner(){if(this.data.busy)return;const title=this.data.bannerTitle.trim(),subtitle=this.data.bannerSubtitle.trim(),weight=Number(this.data.bannerWeight);if(!title||!subtitle){this.setData({error:'请填写广告标题和说明'});return;}if(!Number.isInteger(weight)||weight<0||weight>999){this.setData({error:'权重须为 0–999 的整数'});return;}this.setData({busy:true,error:''});try{let mediaFileID='';if(this.data.bannerMediaType!=='none'){if(this.data.bannerMedia.startsWith('cloud://'))mediaFileID=this.data.bannerMedia;else if(this.data.demoMode)mediaFileID=this.data.bannerMedia;else{const ext=(this.data.bannerMedia.match(/\.[a-z0-9]+$/i)||['.bin'])[0];const up=await wx.cloud.uploadFile({cloudPath:`banners/${Date.now()}-${Math.random().toString(36).slice(2,8)}${ext}`,filePath:this.data.bannerMedia});mediaFileID=up.fileID;this.setData({bannerMedia:mediaFileID});}}await api.call('admin.bannerSave',{id:this.data.bannerId,title,subtitle,weight,enabled:this.data.bannerEnabled,mediaType:this.data.bannerMediaType,mediaFileID});this.newBanner();await this.load(false,true);wx.showToast({title:'已保存'});}catch(e){this.setData({error:e.message});}finally{this.setData({busy:false});}},
 async removeBanner(e){if(this.data.busy)return;const id=e.currentTarget.dataset.id;const r=await wx.showModal({title:'删除广告',content:'删除后该广告立即从客户端首页消失，且无法恢复。如需暂时隐藏，请改用停用。'});if(!r.confirm)return;this.setData({busy:true,error:''});try{await api.call('admin.bannerDelete',{id});if(this.data.bannerId===id)this.newBanner();await this.load(false,true);wx.showToast({title:'已删除'});}catch(err){this.setData({error:err.message});}finally{this.setData({busy:false});}},
 table(e){if(this.data.loading)return;this.setData({tableIndex:Number(e.detail.value),rows:[]});this.load(false,true);},
 async qrcode(){if(this.data.busy)return;const s=this.data.stores[this.data.qrStore];if(!s){this.setData({error:'请先创建门店'});return;}this.setData({busy:true,error:'',qr:''});try{const r=await api.call('admin.qrcode',{storeId:s._id,version:['develop','trial','release'][this.data.versionIndex]});const urls=await wx.cloud.getTempFileURL({fileList:[r.fileID]});const url=urls.fileList[0].tempFileURL;if(!url)throw new Error('获取二维码图片失败，请检查云存储权限');this.setData({qr:url});}catch(e){this.setData({error:e.message});}finally{this.setData({busy:false});}},
 preview(){wx.previewImage({urls:[this.data.qr]});}
});
