const api=require('../../utils/api');const {roles}=require('../../utils/constants');
const tables=['users','stores','conversations','messages','notifications','services','auditLogs'];
Page({data:{tab:'users',users:[],stores:[],rows:[],tables,tableIndex:0,error:'',loading:false,busy:false,page:0,more:false,edit:null,roleOptions:['客户','门店'],roleIndex:0,storeIndex:0,storeId:'',storeName:'',editingStore:false,storeEnabled:true,versions:['开发版','体验版','正式版'],versionIndex:1,qrStore:0,qr:''},
 onShow(){this.start();},async start(){try{const me=await api.guard(['admin']);if(!me)return;this.setData({demoMode:!!me.demoMode});await this.loadStores();await this.load(false,true);}catch(e){this.setData({error:e.message});}},
 async loadStores(){const r=await api.call('admin.stores');this.setData({stores:r.items});},
 tab(e){if(this.data.loading)return;this.setData({tab:e.currentTarget.dataset.tab,page:0,users:[],rows:[],edit:null,error:''});this.load(false,true);},
 async load(e,reset=false){if(this.data.loading)return;this.setData({loading:true,error:''});const page=reset?0:this.data.page+1;try{if(this.data.tab==='users'){const r=await api.call('staff.customers',{page});const users=r.items.map(u=>({...u,roleName:roles[u.role]}));this.setData({users:reset?users:this.data.users.concat(users),page,more:users.length===20});}else if(this.data.tab==='database'){const r=await api.call('admin.inspect',{collection:tables[this.data.tableIndex],page});const rows=r.items.map(x=>({_id:x._id,json:JSON.stringify(x,null,2)}));this.setData({rows:reset?rows:this.data.rows.concat(rows),page,more:rows.length===20});}else{await this.loadStores();this.setData({more:false});}}catch(e){this.setData({error:e.message});}finally{this.setData({loading:false});}},
 editUser(e){const u=this.data.users.find(x=>x._id===e.currentTarget.dataset.id);this.setData({edit:{...u},roleIndex:u.role==='store'?1:0,storeIndex:Math.max(0,this.data.stores.findIndex(s=>s._id===u.storeId))},()=>wx.pageScrollTo({selector:'#user-editor',duration:200}));},
 select(e){this.setData({[e.currentTarget.dataset.key]:Number(e.detail.value)});},userEnabled(e){this.setData({'edit.enabled':e.detail.value});},close(){this.setData({edit:null});},
 async saveUser(){if(this.data.busy)return;const store=this.data.stores[this.data.storeIndex];if(!store){this.setData({error:'请先创建门店'});return;}const r=await wx.showModal({title:'保存账户权限',content:this.data.demoMode?'修改后需重新选择该演示身份，原有会话保留在原门店。':'修改后该用户需重新验证手机号登录。原有会话保留在原门店。'});if(!r.confirm)return;this.setData({busy:true,error:''});try{await api.call('admin.userUpdate',{id:this.data.edit._id,enabled:this.data.edit.enabled,role:this.data.roleIndex===1?'store':'customer',storeId:store._id});this.setData({edit:null});await this.load(false,true);}catch(e){this.setData({error:e.message});}finally{this.setData({busy:false});}},
 input(e){this.setData({[e.currentTarget.dataset.key]:e.detail.value});},storeEnabled(e){this.setData({storeEnabled:e.detail.value});},
 editStore(e){const s=this.data.stores.find(x=>x._id===e.currentTarget.dataset.id);this.setData({storeId:s._id,storeName:s.name,storeEnabled:s.enabled,editingStore:true});},
 newStore(){this.setData({storeId:'',storeName:'',storeEnabled:true,editingStore:false});},
 async saveStore(){if(this.data.busy)return;if(!this.data.storeEnabled){const r=await wx.showModal({title:'停用门店',content:'该门店将不能接收新注册，门店员工登录和相关会话也会停用。'});if(!r.confirm)return;}this.setData({busy:true,error:''});try{await api.call('admin.storeSave',{id:this.data.storeId,name:this.data.storeName,enabled:this.data.storeEnabled});await this.loadStores();this.newStore();wx.showToast({title:'已保存'});}catch(e){this.setData({error:e.message});}finally{this.setData({busy:false});}},
 table(e){if(this.data.loading)return;this.setData({tableIndex:Number(e.detail.value),rows:[]});this.load(false,true);},
 async qrcode(){if(this.data.busy)return;const s=this.data.stores[this.data.qrStore];if(!s){this.setData({error:'请先创建门店'});return;}this.setData({busy:true,error:'',qr:''});try{const r=await api.call('admin.qrcode',{storeId:s._id,version:['develop','trial','release'][this.data.versionIndex]});const urls=await wx.cloud.getTempFileURL({fileList:[r.fileID]});const url=urls.fileList[0].tempFileURL;if(!url)throw new Error('获取二维码图片失败，请检查云存储权限');this.setData({qr:url});}catch(e){this.setData({error:e.message});}finally{this.setData({busy:false});}},
 preview(){wx.previewImage({urls:[this.data.qr]});}
});
